[graph]
all-features = true
targets = ["aarch64-apple-darwin"]

[advisories]
db-urls = ["https://github.com/RustSec/advisory-db"]
unmaintained = "workspace"
yanked = "deny"

[bans]
multiple-versions = "warn"
wildcards = "deny"

[licenses]
version = 2
confidence-threshold = 0.8
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
    "LicenseRef-Slint-Royalty-free-2.0",
    "MIT",
    "Unicode-3.0",
    "Zlib",
]

[licenses.private]
ignore = true
